### ISSUE TITLE
Some problems during running the code

### ISSUE THREAD

**Issue by corwinliu9669** [klightz/splitting#2]
I follow the readme and use "bash train.sh", I find some problems. During round 8, when using compute_A, it raises an error " CUDA out of memory." I currently use 1080ti, I wonder whether I need to use GPU with larger memory size or I need to modify the code.

**Comment by klightz** [comment]
Hi, when I ran the experiment before, it was fine with 12GB GPU memory. I think 1080ti's memory is slightly small and maybe not enough for the last two rounds. One possible solution is to use another dataloader with a smaller batch size when executing the compute_A function for the last two rounds.

**Comment by corwinliu9669** [comment]
Thanks for your help! I use the GPU with larger memory and now I can run the full process. Your work is really excellent!
